##### denite.nvim #####
[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
nnoremap <silent> <Leader>o :<C-u>Denite file_rec<CR>
nnoremap <silent> <Leader>m :<C-u>Denite file_mru<CR>
nnoremap <silent> <Leader>y :<C-u>Denite neoyank<CR>
nnoremap <silent> <Leader>l :<C-u>Denite line<CR>
nnoremap <silent> <Leader>g :<C-u>Denite grep<CR>
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'BufRead'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_event = 'BufRead'
#######################

##### Go #####
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
  let g:deoplete#sources#go#package_dot = 1
  let g:deoplete#sources#go#sort_class = ['package', 'const', 'var', 'type', 'func']
  let g:deoplete#sources#go#use_cache = 1
  let g:deoplete#sources#go#json_directory = $XDG_CACHE_HOME.'/go'
'''
##############

##### Ruby #####
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'
################

##### JavaScript #####
######################

##### Json #####
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
################

##### Toml #####
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
################

##### Haml #####
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'
################

##### slim #####
repo = 'slim-template/vim-slim'
on_ft = 'slim'
################

##### Unite.vim #####
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'unite.vim'
#####################

